### ISSUE TITLE
Tuya python script

### ISSUE THREAD

**Issue by pergolafabio** [rgsilva/stream-to-usb#1]
Hey @rgsilva , sorry to create an issue here, but seems your positivo repo is archived, so wasnt able to create an issue there...

I have a question, i have read your post/blog : https://blog.rgsilva.com/reverse-engineering-positivos-smart-home-app/

verry interesting indeed... i'm using smartlife app:

```
{
"key": "ekmnwp9f5pnxxxxxxxxxxxxxxxxxxx",
"secret": "r3me7ghmxjevrvnpexxxxxxxxxxxxxxxxx",
"secret2": "jfg5rs5kkmrj5mxaxxxxxxxxxxxxxxxxxxxxxxx",
"certSign": "0F:C3:61:99:9C:C0:C3:5B:A8:AC:A5:7D:AA:55:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

I was wondering if you still have that python test script somewhere? To initiate a login and do a basic command like getting the devices list... On the blog you said you would post it, but i dont see it there :-)

thnx in advance and for sharing!!

**Comment by rgsilva** [comment]
The project in question (https://github.com/rgsilva/homeassistant-positivo) is **archived**, and that is the reason why you can't create an issue there. That is intentional and I've archived it about a month ago, as I'm not maintaining it anymore. I most likely do not have the test scripts anymore, but the [API code](https://github.com/rgsilva/homeassistant-positivo/blob/main/tuya/api.py) in that repository can be used for testing as it contains all the necessary methods to get the devices and DPS values.

For HomeAssitant, I suggest you to move instead to Tuya's official implementation as it is more reliable and does not depend on extract keys from the app. While it may not provide all features (at least on the last time I tested it), it is way safer to use. Or, you can just open up your devices and reflash them with local-only firmwares, such as ESPHome and Tasmota.

Note: I edited your issue to hide the keys and secret values.
